base:
  project_name: "Thyroid"
  author: "Harinder Singh Sudwal"

basic:
  random_state: 42
  test_size: 0.2
  target_column_name: classes

data_location:
  notebook_data: notebook\thyroid.csv
  data_artifact: artifacts
  raw_data_filename: raw.csv
  preprocess_file: process_clean.csv
  transformer_file: transformer.csv

  main_model_folder: models
  main_label_encoder: label_encoder.joblib
  model_name: model.joblib
  model_name1: model.pkl

metrics_path:
  metrics_folder: metrics
  metrics_file: metrics.json
  clf_report_filename: classification_report.csv
